In [1]:
import numpy as np

# Define Environment

In [36]:
#Define numer of times that we can play for each turn. Since we have 1000$ to play with slot machines and each turn costs 1$ so we can play 1000 turn.
number_of_truns = 1000
number_of_slot_machines = 6

# Define arrays where we keep our wins(positive rewards) and losses (negative rewards)
Number_of_positive_rewards = np.zeros(number_of_slot_machines)
Number_of_negative_rewards = np.zeros(number_of_slot_machines)

#Define seed for random number genratorto ensure that reults are reproductable
np.random.seed(33)

#Define random conversion rate between 1% to 15% for each slot machine
conversion_rate = np.random.uniform(0.01,0.15, number_of_slot_machines)

# Show conversion rate for each slot machine.Rember that in real world scenario decision makers do not know this information.
for i in range(6):
    print('Conversion rate for slot machine {0} : {1:.2%}'.format(i, conversion_rate[i]))


Conversion rate for slot machine 0 : 4.48%
Conversion rate for slot machine 1 : 7.30%
Conversion rate for slot machine 2 : 6.75%
Conversion rate for slot machine 3 : 4.64%
Conversion rate for slot machine 4 : 13.19%
Conversion rate for slot machine 5 : 3.59%


# Create a Dataset

In [37]:
#Define seed for random number gerator to ensure that result are reproducable
np.random.seed(55)

#Define the dataset matrix with the one row for each turn and one column for each slot machine
# Each item in the matrix shows the outcome of what would happen if we are to paly a particular slot machine that particular turn. A value of 1 indicate that we would win and the value of zero indeicates that we would lose.
#The number of wins for each slot machine is determined by conversion rate.
outcomes = np.zeros((number_of_truns, number_of_slot_machines))

for turn_index in range(number_of_truns): # for each turn
    for slot_machine_index in range(number_of_slot_machines):#for each slot machine
        #get random number between o  and 1.
        # if random number is less than or equal to this slot machine conversion rate , then set the outcome to 1 if not set it to 0.
        if np.random.rand()<= conversion_rate[slot_machine_index]:
            outcomes[turn_index][slot_machine_index] = 1
            
    #disply the first 15row of data
    print(outcomes[:15 , :6])
            
    

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0.

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0.

In [38]:
#Show means conversion rate for each slot machine(column)
for i in range(6):
    print('Means for column{0}:{1:.2%}'.format(i, np.mean(outcomes[:, i])))

Means for column0:4.10%
Means for column1:7.10%
Means for column2:6.30%
Means for column3:4.90%
Means for column4:12.30%
Means for column5:3.40%


# Run simiulation

In [39]:
# we are going to simulate with thompson sampling to determine which slot machie to play in each run:
# for each run
for turn_index in range(number_of_truns):
    index_of_each_machine_to_play = -1
    max_beta = -1
    # determine which slot machine to play for this turn
    for slot_machine_index in range(number_of_slot_machines):
        #define the shape parameters for the beta distribution. The shape will depend on the number of wins and losses that have thus far been observed for this particular slot machine
        a = Number_of_positive_rewards[slot_machine_index]+1
        b = Number_of_negative_rewards[slot_machine_index]+1
        # Get a random value from beta distribution which shape is defined by the number of wins and losses that have thus far been observed for this machine.
        random_beta = np.random.beta(a, b)
        # if this is the largest beta 
        if random_beta > max_beta:
            max_beta = random_beta # update the maximum beta value far observed
            index_of_machine_to_play = slot_machine_index # set the machine to play to the current machine
    
    # play with the selected machine and record winins and losses
    if outcomes[turn_index][index_of_machine_to_play] == 1:
        Number_of_positive_rewards [index_of_machine_to_play] += 1
    else:
        Number_of_negative_rewards[index_of_machine_to_play] += 1
# compute and display the total number of times each slot machine played
number_of_times_played = Number_of_negative_rewards + Number_of_positive_rewards
for slot_machine_index in range(number_of_slot_machines): 
    print('slot machine {0} was played {1} times'.format(slot_machine_index ,number_of_times_played[slot_machine_index] ))
    

    
# identify the best slot machine
print('\n overall conclusion : The best slot machine to play is {}!'.format(np.argmax(number_of_times_played)))

slot machine 0 was played 50.0 times
slot machine 1 was played 42.0 times
slot machine 2 was played 63.0 times
slot machine 3 was played 75.0 times
slot machine 4 was played 695.0 times
slot machine 5 was played 75.0 times

 overall conclusion : The best slot machine to play is 4!


# Compare the performace of Thompson sampling with Random sampling


In [40]:
# compute the total of wins using thompson sampling
total_wins_Thompson_sampling = np.sum(Number_of_positive_rewards)

# Determine how many times we would win if we use random sampling
total_wins_random_sampling = 0
for turn_index in range(number_of_truns):
    index_of_machine_to_play = np.random.randint(0 , number_of_slot_machines)
    if outcomes[turn_index][index_of_each_machine_to_play] ==1 :
        total_wins_random_sampling += 1
        
        
print('Total wins in Thompson sampling : {0:.0f}'.format(total_wins_Thompson_sampling))
print('Total wins in random sampling : {0:.0f}'. format(total_wins_random_sampling))

Total wins in Thompson sampling : 92
Total wins in random sampling : 34
